<div class="grid gap-6 md:grid-cols-2">
    <div><x-input-label for="po_no" value="PO No" /><input id="po_no" name="po_no" type="text" class="input" value="{{ old('po_no', $purchaseOrder->po_no ?? '') }}"><x-input-error :messages="$errors->get('po_no')" class="mt-2" /></div>
    <div><x-input-label for="po_date" value="PO Date" /><input id="po_date" name="po_date" type="date" class="input" value="{{ old('po_date', isset($purchaseOrder) ? $purchaseOrder->po_date?->format('Y-m-d') : now()->format('Y-m-d')) }}" required><x-input-error :messages="$errors->get('po_date')" class="mt-2" /></div>
    <div><x-input-label for="purchase_requisition_id" value="Purchase Requisition" /><select id="purchase_requisition_id" name="purchase_requisition_id" class="select" required><option value="">Select</option>@foreach($purchaseRequisitions as $pr)<option value="{{ $pr->id }}" @selected(old('purchase_requisition_id', $purchaseOrder->purchase_requisition_id ?? '') == $pr->id)>{{ $pr->pr_no }} - {{ $pr->item->name }}</option>@endforeach</select><x-input-error :messages="$errors->get('purchase_requisition_id')" class="mt-2" /></div>
    <div><x-input-label for="vendor_name" value="Vendor Name" /><input id="vendor_name" name="vendor_name" type="text" class="input" value="{{ old('vendor_name', $purchaseOrder->vendor_name ?? '') }}" required><x-input-error :messages="$errors->get('vendor_name')" class="mt-2" /></div>
    <div><x-input-label for="item_id" value="Item" /><select id="item_id" name="item_id" class="select" required><option value="">Select</option>@foreach($items as $item)<option value="{{ $item->id }}" @selected(old('item_id', $purchaseOrder->item_id ?? '') == $item->id)>{{ $item->name }} ({{ $item->item_code }})</option>@endforeach</select><x-input-error :messages="$errors->get('item_id')" class="mt-2" /></div>
    <div><x-input-label for="ordered_qty" value="Ordered Qty" /><input id="ordered_qty" name="ordered_qty" type="number" step="0.01" class="input" value="{{ old('ordered_qty', $purchaseOrder->ordered_qty ?? '') }}" required><x-input-error :messages="$errors->get('ordered_qty')" class="mt-2" /></div>
    <div><x-input-label for="unit_rate" value="Unit Rate" /><input id="unit_rate" name="unit_rate" type="number" step="0.01" class="input" value="{{ old('unit_rate', $purchaseOrder->unit_rate ?? 0) }}" required><x-input-error :messages="$errors->get('unit_rate')" class="mt-2" /></div>
    <div><x-input-label for="status" value="Status" /><select id="status" name="status" class="select" required>@foreach($statuses as $status)<option value="{{ $status }}" @selected(old('status', $purchaseOrder->status ?? 'Pending') == $status)>{{ $status }}</option>@endforeach</select><x-input-error :messages="$errors->get('status')" class="mt-2" /></div>
    <div class="md:col-span-2"><x-input-label for="remarks" value="Remarks" /><textarea id="remarks" name="remarks" class="textarea" rows="4">{{ old('remarks', $purchaseOrder->remarks ?? '') }}</textarea><x-input-error :messages="$errors->get('remarks')" class="mt-2" /></div>
</div>
<div class="mt-6 flex gap-3"><button class="btn-primary">Save</button><a href="{{ route('purchase-orders.index') }}" class="btn-secondary">Cancel</a></div>
