<div class="grid gap-6 md:grid-cols-2">
    <div><x-input-label for="pr_no" value="PR No" /><input id="pr_no" name="pr_no" type="text" class="input" value="{{ old('pr_no', $purchaseRequisition->pr_no ?? '') }}"><x-input-error :messages="$errors->get('pr_no')" class="mt-2" /></div>
    <div><x-input-label for="pr_date" value="PR Date" /><input id="pr_date" name="pr_date" type="date" class="input" value="{{ old('pr_date', isset($purchaseRequisition) ? $purchaseRequisition->pr_date?->format('Y-m-d') : now()->format('Y-m-d')) }}" required><x-input-error :messages="$errors->get('pr_date')" class="mt-2" /></div>
    <div><x-input-label for="category_id" value="Category" /><select id="category_id" name="category_id" class="select" required><option value="">Select</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id', $purchaseRequisition->category_id ?? '') == $category->id)>{{ $category->name }}</option>@endforeach</select><x-input-error :messages="$errors->get('category_id')" class="mt-2" /></div>
    <div><x-input-label for="item_id" value="Item" /><select id="item_id" name="item_id" class="select" required><option value="">Select</option>@foreach($items as $item)<option value="{{ $item->id }}" @selected(old('item_id', $purchaseRequisition->item_id ?? '') == $item->id)>{{ $item->name }} ({{ $item->item_code }})</option>@endforeach</select><x-input-error :messages="$errors->get('item_id')" class="mt-2" /></div>
    <div><x-input-label for="required_qty" value="Required Qty" /><input id="required_qty" name="required_qty" type="number" step="0.01" class="input" value="{{ old('required_qty', $purchaseRequisition->required_qty ?? '') }}" required><x-input-error :messages="$errors->get('required_qty')" class="mt-2" /></div>
    <div><x-input-label for="purpose" value="Purpose" /><select id="purpose" name="purpose" class="select" required><option value="">Select</option>@foreach($purposes as $purpose)<option value="{{ $purpose }}" @selected(old('purpose', $purchaseRequisition->purpose ?? '') == $purpose)>{{ $purpose }}</option>@endforeach</select><x-input-error :messages="$errors->get('purpose')" class="mt-2" /></div>
    <div><x-input-label for="required_for" value="Required For" /><input id="required_for" name="required_for" type="text" class="input" value="{{ old('required_for', $purchaseRequisition->required_for ?? '') }}"><x-input-error :messages="$errors->get('required_for')" class="mt-2" /></div>
    <div><x-input-label for="requested_by" value="Requested By" /><input id="requested_by" name="requested_by" type="text" class="input" value="{{ old('requested_by', $purchaseRequisition->requested_by ?? auth()->user()->name) }}" required><x-input-error :messages="$errors->get('requested_by')" class="mt-2" /></div>
    <div><x-input-label for="status" value="Status" /><select id="status" name="status" class="select" required>@foreach($statuses as $status)<option value="{{ $status }}" @selected(old('status', $purchaseRequisition->status ?? 'Pending') == $status)>{{ $status }}</option>@endforeach</select><x-input-error :messages="$errors->get('status')" class="mt-2" /></div>
    <div class="md:col-span-2"><x-input-label for="remarks" value="Remarks" /><textarea id="remarks" name="remarks" class="textarea" rows="4">{{ old('remarks', $purchaseRequisition->remarks ?? '') }}</textarea><x-input-error :messages="$errors->get('remarks')" class="mt-2" /></div>
</div>
<div class="mt-6 flex gap-3"><button class="btn-primary">Save</button><a href="{{ route('purchase-requisitions.index') }}" class="btn-secondary">Cancel</a></div>
