<x-app-layout>
    <x-slot name="header"><x-partials.page-header title="Reports & Stock Balance" description="Filter PR, PO, receipts, issues, balances, and analytical reports." /></x-slot>
    <div class="space-y-6">
        <div class="card">
            <form method="GET" class="grid gap-4 md:grid-cols-4 xl:grid-cols-5">
                <div><x-input-label for="date_from" value="Date From" /><input id="date_from" name="date_from" type="date" class="input" value="{{ $filters['date_from'] ?? '' }}"></div>
                <div><x-input-label for="date_to" value="Date To" /><input id="date_to" name="date_to" type="date" class="input" value="{{ $filters['date_to'] ?? '' }}"></div>
                <div><x-input-label for="category_id" value="Category" /><select id="category_id" name="category_id" class="select"><option value="">All</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(($filters['category_id'] ?? '') == $category->id)>{{ $category->name }}</option>@endforeach</select></div>
                <div><x-input-label for="item_id" value="Item" /><select id="item_id" name="item_id" class="select"><option value="">All</option>@foreach($items as $item)<option value="{{ $item->id }}" @selected(($filters['item_id'] ?? '') == $item->id)>{{ $item->name }}</option>@endforeach</select></div>
                <div><x-input-label for="store_id" value="Store" /><select id="store_id" name="store_id" class="select"><option value="">All</option>@foreach($stores as $store)<option value="{{ $store->id }}" @selected(($filters['store_id'] ?? '') == $store->id)>{{ $store->name }}</option>@endforeach</select></div>
                <div><x-input-label for="pr_no" value="PR No" /><input id="pr_no" name="pr_no" type="text" class="input" value="{{ $filters['pr_no'] ?? '' }}"></div>
                <div><x-input-label for="po_no" value="PO No" /><input id="po_no" name="po_no" type="text" class="input" value="{{ $filters['po_no'] ?? '' }}"></div>
                <div><x-input-label for="person_name" value="Person Name" /><input id="person_name" name="person_name" type="text" class="input" value="{{ $filters['person_name'] ?? '' }}"></div>
                <div><x-input-label for="purpose" value="Purpose" /><input id="purpose" name="purpose" type="text" class="input" value="{{ $filters['purpose'] ?? '' }}"></div>
                <div><x-input-label for="status" value="Status" /><input id="status" name="status" type="text" class="input" value="{{ $filters['status'] ?? '' }}"></div>
                <div class="md:col-span-4 xl:col-span-5 flex gap-3"><button class="btn-primary">Apply Filters</button><a href="{{ route('reports.index') }}" class="btn-secondary">Reset</a></div>
            </form>
        </div>

        <div class="card overflow-x-auto">
            <h2 class="mb-4 text-lg font-semibold">Store Balance Report</h2>
            <table class="min-w-full text-sm"><thead><tr class="border-b border-slate-200 text-left text-slate-500"><th class="pb-3 pr-3">Category</th><th class="pb-3 pr-3">Item</th><th class="pb-3 pr-3">Store</th><th class="pb-3 pr-3">PR No</th><th class="pb-3 pr-3">PO No</th><th class="pb-3 pr-3">Received</th><th class="pb-3 pr-3">Issued</th><th class="pb-3">Balance</th></tr></thead><tbody>@forelse($storeBalances as $row)<tr class="border-b border-slate-100"><td class="py-3 pr-3">{{ $row->category_name }}</td><td class="py-3 pr-3">{{ $row->item_name }}</td><td class="py-3 pr-3">{{ $row->store_name }}</td><td class="py-3 pr-3">{{ $row->pr_no }}</td><td class="py-3 pr-3">{{ $row->po_no }}</td><td class="py-3 pr-3">{{ number_format($row->total_received, 2) }}</td><td class="py-3 pr-3">{{ number_format($row->total_issued, 2) }}</td><td class="py-3">{{ number_format($row->balance_qty, 2) }}</td></tr>@empty<tr><td colspan="8" class="py-8 text-center text-slate-500">No balance data found.</td></tr>@endforelse</tbody></table>
        </div>

        <div class="grid gap-6 xl:grid-cols-2">
            <div class="card overflow-x-auto"><h2 class="mb-4 text-lg font-semibold">PR Report</h2><table class="min-w-full text-sm"><thead><tr class="border-b border-slate-200 text-left text-slate-500"><th class="pb-3 pr-3">PR No</th><th class="pb-3 pr-3">Date</th><th class="pb-3 pr-3">Item</th><th class="pb-3 pr-3">Qty</th><th class="pb-3">Status</th></tr></thead><tbody>@forelse($purchaseRequisitions as $row)<tr class="border-b border-slate-100"><td class="py-3 pr-3">{{ $row->pr_no }}</td><td class="py-3 pr-3">{{ $row->pr_date?->format('d M Y') }}</td><td class="py-3 pr-3">{{ $row->item->name }}</td><td class="py-3 pr-3">{{ number_format($row->required_qty, 2) }}</td><td class="py-3">{{ $row->status }}</td></tr>@empty<tr><td colspan="5" class="py-8 text-center text-slate-500">No PR data found.</td></tr>@endforelse</tbody></table></div>
            <div class="card overflow-x-auto"><h2 class="mb-4 text-lg font-semibold">PO Report</h2><table class="min-w-full text-sm"><thead><tr class="border-b border-slate-200 text-left text-slate-500"><th class="pb-3 pr-3">PO No</th><th class="pb-3 pr-3">Date</th><th class="pb-3 pr-3">Vendor</th><th class="pb-3 pr-3">Qty</th><th class="pb-3">Status</th></tr></thead><tbody>@forelse($purchaseOrders as $row)<tr class="border-b border-slate-100"><td class="py-3 pr-3">{{ $row->po_no }}</td><td class="py-3 pr-3">{{ $row->po_date?->format('d M Y') }}</td><td class="py-3 pr-3">{{ $row->vendor_name }}</td><td class="py-3 pr-3">{{ number_format($row->ordered_qty, 2) }}</td><td class="py-3">{{ $row->status }}</td></tr>@empty<tr><td colspan="5" class="py-8 text-center text-slate-500">No PO data found.</td></tr>@endforelse</tbody></table></div>
            <div class="card overflow-x-auto"><h2 class="mb-4 text-lg font-semibold">Stock Receiving Report</h2><table class="min-w-full text-sm"><thead><tr class="border-b border-slate-200 text-left text-slate-500"><th class="pb-3 pr-3">GRN</th><th class="pb-3 pr-3">PO</th><th class="pb-3 pr-3">Item</th><th class="pb-3">Qty</th></tr></thead><tbody>@forelse($stockReceipts as $row)<tr class="border-b border-slate-100"><td class="py-3 pr-3">{{ $row->grn_no }}</td><td class="py-3 pr-3">{{ $row->purchaseOrder->po_no }}</td><td class="py-3 pr-3">{{ $row->item->name }}</td><td class="py-3">{{ number_format($row->received_qty, 2) }}</td></tr>@empty<tr><td colspan="4" class="py-8 text-center text-slate-500">No receipt data found.</td></tr>@endforelse</tbody></table></div>
            <div class="card overflow-x-auto"><h2 class="mb-4 text-lg font-semibold">Stock Issue Report</h2><table class="min-w-full text-sm"><thead><tr class="border-b border-slate-200 text-left text-slate-500"><th class="pb-3 pr-3">Issue</th><th class="pb-3 pr-3">Store</th><th class="pb-3 pr-3">Person</th><th class="pb-3">Qty</th></tr></thead><tbody>@forelse($stockIssues as $row)<tr class="border-b border-slate-100"><td class="py-3 pr-3">{{ $row->issue_no }}</td><td class="py-3 pr-3">{{ $row->store->name }}</td><td class="py-3 pr-3">{{ $row->issued_to_person }}</td><td class="py-3">{{ number_format($row->issue_qty, 2) }}</td></tr>@empty<tr><td colspan="4" class="py-8 text-center text-slate-500">No issue data found.</td></tr>@endforelse</tbody></table></div>
            <div class="card overflow-x-auto"><h2 class="mb-4 text-lg font-semibold">Item Ledger</h2><table class="min-w-full text-sm"><thead><tr class="border-b border-slate-200 text-left text-slate-500"><th class="pb-3 pr-3">Item</th><th class="pb-3 pr-3">Store</th><th class="pb-3 pr-3">Received</th><th class="pb-3 pr-3">Issued</th><th class="pb-3">Balance</th></tr></thead><tbody>@forelse($itemLedger as $row)<tr class="border-b border-slate-100"><td class="py-3 pr-3">{{ $row->item_name }}</td><td class="py-3 pr-3">{{ $row->store_name }}</td><td class="py-3 pr-3">{{ number_format($row->total_received, 2) }}</td><td class="py-3 pr-3">{{ number_format($row->total_issued, 2) }}</td><td class="py-3">{{ number_format($row->balance_qty, 2) }}</td></tr>@empty<tr><td colspan="5" class="py-8 text-center text-slate-500">No ledger data found.</td></tr>@endforelse</tbody></table></div>
            <div class="card overflow-x-auto"><h2 class="mb-4 text-lg font-semibold">Person-wise Handover Report</h2><table class="min-w-full text-sm"><thead><tr class="border-b border-slate-200 text-left text-slate-500"><th class="pb-3 pr-3">Person</th><th class="pb-3 pr-3">Transactions</th><th class="pb-3">Issued Qty</th></tr></thead><tbody>@forelse($personWise as $row)<tr class="border-b border-slate-100"><td class="py-3 pr-3">{{ $row->issued_to_person }}</td><td class="py-3 pr-3">{{ $row->total_transactions }}</td><td class="py-3">{{ number_format($row->total_issue_qty, 2) }}</td></tr>@empty<tr><td colspan="3" class="py-8 text-center text-slate-500">No person-wise data found.</td></tr>@endforelse</tbody></table></div>
            <div class="card overflow-x-auto"><h2 class="mb-4 text-lg font-semibold">Purpose-wise Usage Report</h2><table class="min-w-full text-sm"><thead><tr class="border-b border-slate-200 text-left text-slate-500"><th class="pb-3 pr-3">Purpose</th><th class="pb-3 pr-3">Transactions</th><th class="pb-3">Issued Qty</th></tr></thead><tbody>@forelse($purposeWise as $row)<tr class="border-b border-slate-100"><td class="py-3 pr-3">{{ $row->usage_purpose }}</td><td class="py-3 pr-3">{{ $row->total_transactions }}</td><td class="py-3">{{ number_format($row->total_issue_qty, 2) }}</td></tr>@empty<tr><td colspan="3" class="py-8 text-center text-slate-500">No purpose-wise data found.</td></tr>@endforelse</tbody></table></div>
            <div class="card overflow-x-auto"><h2 class="mb-4 text-lg font-semibold">Category-wise Stock Report</h2><table class="min-w-full text-sm"><thead><tr class="border-b border-slate-200 text-left text-slate-500"><th class="pb-3 pr-3">Category</th><th class="pb-3 pr-3">Received</th><th class="pb-3 pr-3">Issued</th><th class="pb-3">Balance</th></tr></thead><tbody>@forelse($categoryWise as $row)<tr class="border-b border-slate-100"><td class="py-3 pr-3">{{ $row->category_name }}</td><td class="py-3 pr-3">{{ number_format($row->total_received, 2) }}</td><td class="py-3 pr-3">{{ number_format($row->total_issued, 2) }}</td><td class="py-3">{{ number_format($row->balance_qty, 2) }}</td></tr>@empty<tr><td colspan="4" class="py-8 text-center text-slate-500">No category-wise data found.</td></tr>@endforelse</tbody></table></div>
        </div>
    </div>
</x-app-layout>
